### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [iredmail/blacklist_rdns#1]
It is possible to migrate the personal account to organization?
https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by Neustradamus** [comment]
@iredmail here too!

Linked to:
- https://github.com/iredmail/blacklist_rdns/issues/1
- https://github.com/iredmail/iredadmin-pro-translation/issues/8
- https://github.com/iredmail/mlmmjadmin/issues/2
- https://github.com/iredmail/iredmail_autologon/issues/1

**Comment by iredmail** [comment]
I don’t want to migrate, please stop spamming.

**Comment by Neustradamus** [comment]
You have not replied me since December, it is not a spamming :)
Why?
It is free and really better, And iRedMail is a project...

**Comment by iredmail** [comment]
Because i'm not interested in such change right now, i appreciate your suggestion, but no.
Please stop creating issues in every repo to suggest me, this is annoying.
